const comments = [
  {
    id: 1,
    name: 'Kelly Stone',
    comment: 'is it true? 😱',
    likes: '54k',
    time: 1,
    isSubComment: false,
  },
  {
    id: 2,
    name: 'Wu Jin',
    comment: '🥇 TOP',
    likes: '',
    time: 4,
    isSubComment: false,
  },
  {
    id: 3,
    name: 'Jean Bellmore',
    comment: '@AJPuccino try this NOW',
    likes: '8k',
    time: 6,
    isSubComment: false,
  },
  {
    id: 4,
    name: 'AJ Puccino',
    comment: 'ahhah 😃 Cool',
    likes: '4k',
    time: 5,
    isSubComment: true,
  },
  {
    id: 5,
    name: 'Nathan Stork',
    comment: 'YEAH!!! 💰💰💰',
    likes: '28k',
    time: 11,
    isSubComment: false,
  },
  {
    id: 6,
    name: 'Milana Rassakowska',
    comment: 'Nice test, thanks',
    likes: '33k',
    time: 13,
    isSubComment: false,
  },
  {
    id: 7,
    name: 'Kurt Kelsey',
    comment: '🙈 🙈 🙈',
    likes: '31k',
    time: 11,
    isSubComment: true,
  },
  {
    id: 8,
    name: 'Omar Hashmi',
    comment: 'This is a miracle 🙏',
    likes: '39k',
    time: 15,
    isSubComment: false,
  },
  {
    id: 9,
    name: 'Andy Lane',
    comment: 'Thank you for description, now I know.....',
    likes: '45k',
    time: 13,
    isSubComment: true,
  },
  {
    id: 10,
    name: 'Sven Tilden',
    comment: 'Awesome. My wife got better scores than me. Should I quit my job now?...🤣',
    likes: '69k',
    time: 6,
    isSubComment: true,
  },
  {
    id: 11,
    name: 'Carrie Swanson',
    comment: 'My life has changed 😍 thanks to this!!! Internet, I love you',
    likes: '54k',
    time: 18,
    isSubComment: false,
  },
  {
    id: 12,
    name: 'Mike Lacey',
    comment: 'Was sceptical at the start, but then.....wow.',
    likes: '69k',
    time: 21,
    isSubComment: false,
  },
  {
    id: 13,
    name: 'Ni Chang',
    comment: 'Me too!!!',
    likes: '60k',
    time: 15,
    isSubComment: true,
  },
];

export default comments;
